#!/usr/bin/env python
#-*- coding:utf-8 -*-

"""
This script is automatically generated by 'command sat test etc...'
from ...salomeTools/src/test/scriptTemplate.py
"""

import os
import sys
import traceback
import os.path
import time as THEBIGTIME


# set path
toolsWay = r'${toolsWay}'
resourcesWay = r'${resourcesWay}'
outWay = r'${sessionDir}'
tmpDir = r'${tmpDir}'

listTest = ${listTest}
ignore = ${ignore}

sys.path.append(toolsWay)
from TOOLS import TOOLS_class
my_tools = TOOLS_class(resourcesWay, tmpDir, toolsWay)

from TOOLS import SatNotApplicableError

# set environement variables
os.environ['TT_BASE_RESSOURCES'] = resourcesWay
sys.path.append(resourcesWay)

__stdout__ = sys.stdout
__stderr__ = sys.stderr

with open(r'${resultFile}', 'w') as exec_result:
  exec_result.write('Open\n')

  for test in listTest:
    with open(os.path.join(outWay, test[:-3] + ".result.py"), "w") as pylog:
      with open(os.path.join(outWay, test[:-3] + ".out.py"), "w") as testout:
        my_tools.init()
        sys.stdout = testout
        sys.stderr = testout

        pylog.write('#-*- coding:utf-8 -*-\n')
        exec_result.write("Run %s " % test)
        exec_result.flush()

        try:
            timeStart = THEBIGTIME.time()
            execfile(os.path.join(outWay, test), globals(), locals())
            timeTest = THEBIGTIME.time() - timeStart
        except SatNotApplicableError as ex:
            status = "NA"
            reason = str(ex)
            exec_result.write("NA\n")
            timeTest = THEBIGTIME.time() - timeStart
            pylog.write('status = "NA"\n')
            pylog.write('time = "' + timeTest.__str__() + '"\n')
            pylog.write('callback = "%s"\n' % reason)
        except Exception as ex:
            status = "KO"
            reason = ""
            if ignore.has_key(test):
                status = "KF"
                reason = "Known Failure = %s\n\n" % ignore[test]
            exec_result.write("%s\n" % status)
            timeTest = THEBIGTIME.time() - timeStart
            pylog.write('status = "%s" \n' % status)
            pylog.write('time = "' + timeTest.__str__() + '"\n')
            pylog.write('callback="""' + reason)
            exc_type, exc_value, exc_traceback = sys.exc_info()
            traceback.print_exception(exc_type,
                                      exc_value,
                                      exc_traceback,
                                      None,
                                      file=pylog)
            pylog.write('"""\n')
        else:
            exec_result.write("OK\n")
            pylog.write('status = "OK"\n')
            pylog.write('time = "' + timeTest.__str__() + '"\n')

        pass
        # testout.close()

      sys.stdout = __stdout__
      sys.stderr = __stderr__
      my_tools.writeInFiles(pylog)
      pass
      # pylog.close()

  exec_result.write('Close\n')
  pass
  # exec_result.close()

if 'PY' not in '${sessionName}':
    import salome_utils
    #killScript = os.path.join(os.environ['KERNEL_ROOT_DIR'],
    #                          'bin',
    #                          'salome',
    #                          'killSalome.py')
    #cmd = '{python} {killScript} {port}'.format(python=os.environ['PYTHONBIN'],
    #                                       killScript=killScript,
    #                                       port=salome_utils.getPortNumber())
    cmd = 'killSalome.py {port}'.format( port=salome_utils.getPortNumber())
    os.system(cmd)

