name: Run Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      run_test:
        description: 'Run non regression tests ?'
        type: boolean
        required: true
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment variables
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        python AllTestLauncherSat.py
